- core/lib/class.plx.show.php
Cette ancre permet de pointer directement sur le contenu de l'article
en sautant le chapô qui a été lu en page d'accueil.
> Ajout du paramètre optionnel anchor

- core/admin/foot.php
- core/lib/js.src/mediasManager.js
Image d'accroche dans article.php:
Pour lancer le **mediaManager**, il est préférable de donner une adresse url absolue à **urlManager**, ou une adresse relative par rapport à racine.
Le remplacement de **onclick** dans medias.php est très lourd. En utilisant **addEventListener** sur tbody, on simplifie bien les choses.
Avant d'appeler **callback**, il est plus pertinent de vérifier que c'est bien une **function** plutôt que de vérifier que la valeur n'est pas une chaine vide.
> Optimisation appel mediasManager pour image d'accroche

- core/lib/class.plx.show.php
Modification de la méthode `templateCss` pour permettre l'utilisation automatique de fichier CSS minifier si ceux-ci sont disponibles, sinon, utiliser les fichiers classique.
Les fichiers minifiés doivent terminer par `min.css`, par exemple : `mon_style.min.css`
> Inclure des fichiers minifier si disponibles

- core/lang/de/core.php
- core/lang/en/core.php
- core/lang/es/core.php
- core/lang/fr/core.php
- core/lang/it/core.php
- core/lang/nl/core.php
- core/lang/oc/core.php
- core/lang/pl/core.php
- core/lang/pt/core.php
- core/lang/ro/core.php
- core/lang/ru/core.php
- core/lib/class.plx.utils.php
- install.php
À l'installation, la disponibilité de la bibliothèque XML n'est pas testée. La validation de l'installeur aboutit à une page blanche avec l'erreur suivante dans le log : `Call to undefined function xml_parser_create()`
J'ai ajouté le test de la bibliothèque XML sur le modèle du test de GD. Si cela convient, je rajouterai les autres traductions.
> Test lib XML à l'installation

- core/lang/en/core.php
- core/lang/fr/core.php
- core/lib/class.plx.date.php
- core/lib/class.plx.show.php
- Cumul mensuel des archives sur une **période glissante** de 12 mois.
- Création constante plxShow::ARCH_LIST_OPTION pour utiliser archList dans un &lt;select&gt;.
- Constantes supplementaires pour plx::getCalendar(..).
> Periode glissante (12 mois) pour plxShow::archList.

- core/admin/theme/theme.css
Mon pull-request ne fait aucune référence aux tables #categories-table et #statics-table pour trier les rangées des tableaux avec la souris.
> Suppression regles CSS obsoletes pour le tri des rangees de tableaux

- core/admin/parametres_infos.php
- core/admin/theme/theme.css
- core/lib/class.plx.admin.php
plxAmin::checkMaj accepte maintenant les paramètres $url, $href, $caption.
En cas d'échec, on utilise Javascript sur le navigateur et on interroge Github
ou un autre serveur avec le protocole JSON-P.
Remplace le précèdent PR check_maj2 ( mauvaise manip sur Github)
> Test si maj PluXml dispo (cas allow_url_fopen = false)

- core/admin/parametres_plugin.php
- core/admin/parametres_plugins.php
- core/admin/plugin.php
- core/admin/theme/theme.css
- core/lang/de/admin.php
- core/lang/en/admin.php
- core/lang/es/admin.php
- core/lang/fr/admin.php
- core/lang/it/admin.php
- core/lib/class.plx.plugins.php
Voir fil de discussion  http://forum.pluxml.org/viewtopic.php?id=6159
Prise en compte de la balise &lt;usage&gt; dans les fichiers infos.xml des plugins pour charger uniquement les plugins activés nécessaires soit côté admin, soit côté site.
La balise peut prendre les valeurs admin, site, ou être vide ou absente (rétro-compatilité.
A la mise à jour, enregistrer la liste des plugins activés pour prendre en compte la nouvelle balise.
Côté site, on peut voir la liste des plugins réellement chargés en ajoutant la ligne suivante à la fin du fichier footer.php du thème courant :
`<?php echo "\n"; ?>`
copies d'écran
https://flic.kr/p/HDQA8c
https://flic.kr/p/21fErAF
> Sélection des plugins à charger selon côté admin ou côté site

- core/lib/class.plx.show.php
- themes/defaut/css/theme.css
- themes/defaut/sidebar.php
__Annule et remplace le Pull-request #136.__
Pour trier les tags, on utilise un tableau, indexé sur les tags, de compteurs.
D'où un tri plus simple.
Par défaut, le tri est aléatoire. On peut également trier par popularité.
Le tri alpha se fait sur les clés du tableau précèdent.
Pour le format par défaut, on utilise une constante de class.
Mise à l'échelle pour la taille des caractères (font-size), avec gestion
de la couleur.
Pour traiter le format en une passe, on passe 2 tableaux en parametres à
str_replace(...) et on affiche le résultat directement.
En mode home, on surligne les tags des articles listés, comme en mode
article.
> Amélioration de plxShow::tagList(..)

- core/lib/class.plx.show.php
Lorsque l'on est ni dans une page article, ni dans une page de tags, le $status "noactive" n'était pas renvoyé.
> tag status noactive par défaut

- core/lib/class.plx.show.php
scope plxShow staticList() + theme defaut
> Add (sub-)menu class : Fix group menu lists

- core/lib/class.plx.utils.php
Correction du dernier PR de Sudwebdesign :
$new_content est initialisé comme un string et on l'utilise comme un array. Et PHP ne bronche pas
> Fix plxUtils::unSlash()

- core/admin/prepend.php
- index.php
- install.php
- readme/CHANGELOG
- update/index.php
FIX https://github.com/pluxml/PluXml/issues/253
> FIX #253 Faille XSS session cookie

- core/admin/parametres_infos.php
- core/lib/class.plx.admin.php
- core/lib/class.plx.utils.php
Utilise Javascript pour vérifier la mise à jour de PluXml si l'hébergeur du site ne permet d'utiliser curl ou file_get_contents pour les Urls.
Valider avant le pull-request  "Fix plxUtils::getLangs() #370"
> Check maj 200110

- core/admin/medias.php
- core/admin/theme/theme.css
- core/lib/medias.js
Voir fil de discussion ici : https://forum.pluxml.org/discussion/4532/plugin-tinymce-editeur-pour-articles-et-pages-statiques#latest
Les icônes employées dans le gestionnaire de médias ne sont pas très explcites. Il n'est donc pas évident de comprendre qu'une icône permet de copier d'un clic l'url d'une image.
Il existe des entities HTML plus explicites avec ce PR.
Autre souci résolu : la toucher "entrée" ne fonctionne pas quand on renomme une image et oblige à cliquer sur un bouton avec la souris. => perte de temps
Toute la floppée de onclick pour les images est remplacée par un écouteur d'évènements sur la balise "<tbody>". Ca simplifie la gestion et cela va certainement plus vite.
> Medias icons 2003

- core/admin/medias.php
- core/admin/parametres_users.php
- core/admin/prepend.php
- core/admin/top.php
- core/lib/config.php
PHP 5.6 permet de créer des constantes tableaux !
PROFIL_NAMES est utilisé dans top.php et parametres_user.php
Et éventuellement dans des plugins pour fixer certains droits
> Création des constantes PROFIL_NAMES, IMG_REDIM et IMG_THUMB

- core/admin/parametres_themes.php
- core/lang/de/admin.php
- core/lang/en/admin.php
- core/lang/es/admin.php
- core/lang/fr/admin.php
- core/lang/it/admin.php
- core/lang/nl/admin.php
- core/lang/oc/admin.php
- core/lang/pl/admin.php
- core/lang/pt/admin.php
- core/lang/ro/admin.php
- core/lang/ru/admin.php
- core/lib/config.php
Attention à la syntaxe allemande
http:// => https:// !!!
> Extraction de l'Url des ressources dans les traductions

- core/lib/class.plx.date.php
- core/lib/class.plx.show.php
Une nouvelle fois, on privilégie l'emploi de strtr() à str_replace() pour des remplacements multiples.
C'est plus rapide et plus fiable.
> Remplacer multiples str_replace par strtr

- core/admin/get_oauth_token.php
- core/admin/parametres_affichage.php
- core/admin/parametres_avances.php
- core/admin/parametres_base.php
- core/admin/parametres_themes.php
- core/admin/statiques.php
- core/lib/class.plx.admin.php
Inutile de passer $plxAdmin->aConf à la fonction plxAdmin::editConfiguration() !
Génére systématiquement le fichier .htaccess si urlrewrite activé ( isset() != !empty() )
> plxAdmin::editConfiguration()

- themes/defaut/css/theme.css
Autorise l'affichage temporaire avec les fontes natives, et les remplaces par celle du thème une fois chargée.
Accélère nettement l'affichage sur les connexions à faibles débits.
Et complètement transparent pour PluXML.
> Autorise les fontes natives lors du chargement

- core/admin/parametres_avances.php
Tout est dans le titre
P.S. : Il faut mettre la police Fontello à jour par rapport à la branche master. Il manque des icônes dans la sidebar admin et dans auth.php.
> Fix $disabled dans parametres_avancees.php

- core/lib/config.php
Gestion plus stricte de l'autoloader :
Ne gère que les class de PluXml dont le nom commence par plx ou Plx, suivi d'une majuscule.
Evite des conflits avec des class créés par des plugins qui oublient de faire leurs "include".
> Fix spl_autoload_register() dans config.php

- core/lang/de/core.php
- core/lang/en/core.php
- core/lang/es/core.php
- core/lang/fr/core.php
- core/lang/it/core.php
- core/lang/nl/core.php
- core/lang/oc/core.php
- core/lang/pl/core.php
- core/lang/pt/core.php
- core/lang/ro/core.php
- core/lang/ru/core.php
- core/lib/class.plx.motor.php
- core/lib/class.plx.show.php
- themes/defaut/article.php
- themes/defaut/css/theme.css
- themes/defaut/header.php
Permet de passer aux articles précèdent, suivant, premier et dernier
pour la catégorie, le mot-clé ou l'archive sélectionnée.
Ajoute les balises link de navigation dans <head>
Ainsi que l'adresse canonicale.
> Ajoute la navigation dans la page article côté site

- core/admin/auth.php
- core/admin/foot.php
- core/admin/get_oauth_token.php
- core/admin/index.php
- core/admin/parametres_plugins.php
- core/admin/parametres_themes.php
- core/admin/prepend.php
- core/admin/top.php
- core/lib/class.plx.feed.php
- core/lib/class.plx.medias.php
- core/lib/class.plx.motor.php
- core/lib/class.plx.show.php
- core/lib/config.php
- feed.php
- index.php
- install.php
- sitemap.php
- themes/defaut/footer.php
- update/index.php
Simplification des liens, notamment dans le menu admin.
Creation de la constante PLX_ADMIN_PATH.
Il est ainsi possible de renommer le dossier core/admin. En ajustant cette constante, le site reste fonctionnel. 
Creation de la fonction plxShow::admin() pour afficher l'URL accessant au back-office. A utiliser dans le thème.
Evite aux hackers de savoir si un site est propulsé par PluXml en tentant d'accéder à la page index du dossier http://mon-site.com/core/admin/.
> Admin links

- core/lib/class.plx.motor.php
Par contre, le lien "first" n'est plus affiché à cette position
Idem à l'autre nout de la série avec "next" et "last".
Voir discussion dans le forum avec assodefis le 26 mai :
https://forum.pluxml.org/discussion/6723/plxshow-navprevious-et-plxshow-navnext#latest
> Le lien "prev" reste affiché si on est à l'article n°2 dans la série

- themes/defaut/header.php
In order to improve accessibility compliancy, an aria-label need to be added.
"Provide a valid label for form fields" warning from https://www.webaccessibility.com test.
When on-screen labels are present, they must be programmatically associated with form fields. When on-screen labels are not present, form fields must be given an accessible label.
When form fields do not have a programmatic (accessible) label, assistive technologies may incorrectly render the label or provide no label at all to users. When labels are not present or are incorrect, users of assistive technologies may not be able to complete a form.
The HTML5 specification has a new form field attribute called <code>placeholder</code>. This represents a label or hint, such as a word or short phrase, that is assigned to a …
> add aria-label for accessibility

- core/admin/auth.php
- core/lang/de/install.php
- core/lang/en/admin.php
- core/lang/en/install.php
- core/lang/es/admin.php
- core/lang/es/install.php
- core/lang/fr/admin.php
- core/lang/fr/install.php
- core/lang/it/admin.php
- core/lang/it/install.php
- core/lang/nl/install.php
- core/lang/oc/admin.php
- core/lang/oc/install.php
- core/lang/pl/install.php
- core/lang/pt/install.php
- core/lang/ro/install.php
- core/lang/ru/install.php
- core/lib/class.plx.admin.php
- core/lib/config.php
Dans plxAdmin::sendLostPasswordEmail(),
remplacer 'core/admin/' par constantes
Refacto plxAmdin::verifyLostPasswordToken()
Emploi traductions existantes : remplacer L_PROFIL_PASSWORD par
L_PASSWORD. Idem L_PROFIL_CONFIRM_PASSWORD.
Suppression doublon clé de traduction L_PASSWORD dans core/lang/??/install.php
Utilisation espaces insécables pour page authetification.
> Diverses corrections pour l'authentification

- core/admin/auth.php
- core/admin/foot.php
- core/admin/theme/css/theme.css
- core/lib/mediasManager.js
Attribut required pour tous les champs de saisie de core/admin/auth.php
Si thumbnail défini pour le site, afficher à la place du logo de PluXml
sur auth.php
Fix mediasManager (mauvaise url pour popup)
> Modif page authentification

- core/lib/class.plx.admin.php
- core/lib/class.plx.feed.php
- core/lib/class.plx.motor.php
Fix plxAdmin::getInstance() (parent::$instance)
Fix test $_SESSION['user'] dans plxAdmin::editUsers()
Actuellement dans le back-office, tous les appels à plxMotor::getIsntance() créent une nouvelle instance plxMotor mais n'utilisent pas l'instance plxAdmin existante. D'où tentative de créer à nouveau la constante PLX_SITE_LANG dans plxAdmin::__construct()
> $instance de plxAdmin est hérité de plxMotor !

- core/admin/parametres_users.php
With autocomplete="new-password" attribute = all empty password fields and browser save password notice never appear.
> No autofill & save pass browser box on parametres_users.php

- core/lib/class.plx.show.php
* Fix missing plxMotor
* Fix Notice: Undefined variable: bypage (line 1760) : other modes than categorie, tags & archives : like ?article1/myfirstart
* Fix $title = ucfirst('L_ARCHIVES')
* (maybe bad) Fix Notice: Undefined index: previous : preview mode or direct access like : index.php?article1
```
artNavigationRange() {
if(empty($_SESSION['previous'])) return;
```
> Fixes for plxShow artNavigation[Range]() & 3 new hooks

- README.md
- core/admin/medias.php
- core/admin/theme/css/theme.css
- core/lang/de/core.php
- core/lang/en/core.php
- core/lang/es/core.php
- core/lang/fr/core.php
- core/lang/it/core.php
- core/lang/nl/core.php
- core/lang/oc/core.php
- core/lang/pl/core.php
- core/lang/pt/core.php
- core/lang/ro/core.php
- core/lang/ru/core.php
- core/lib/class.plx.admin.php
- core/lib/class.plx.feed.php
- core/lib/class.plx.medias.php
- core/lib/class.plx.motor.php
- core/lib/class.plx.plugins.php
- core/lib/class.plx.updater.php
- core/lib/class.plx.utils.php
- core/lib/config.php
- install.php
- readme/CHANGELOG
- themes/defaut/css/theme.css
- update/index.php
Voir post dans forum :
https://forum.pluxml.org/discussion/6811/probleme-daffichage-des-plugins-peut-etre-resolut#latest
> Tentative de renommer le nom mal-formé d'un dossier de plugin (from Github for E.G.)

- core/lang/en/admin.php
manque ";" dans core/lan/en/admin.php
> Fix typo core/lang/en/admin.php

- core/lang/en/admin.php
- core/lib/class.plx.show.php
Fix: plxShow::artTags gère les tags avec les lettres accentuées
Emploi plxUtils::urlify() pour les tags de l'article
Optimisation de l'emploi de array_map();
Fix: Corrige Bug si aucune catégorie connue dans plxShow::artCat
> Plxshow arttags 201107

- core/lib/class.plx.show.php
Fix gestion contenu dans liste commentaires
On calcule uniquement les champs utiles à $format
Utilisation de $max dans la boucle et test au bon endroit
Optimisation code avec preg_match_all
Emploi de PHP_EOL dans les listes pour lastArtList, lastComList, archList, catList, tagsList.
Rend le code source de la page HTML générée plus lisible
---
dépôt PluXml : branche master renommée en 6.0
remplace PR#503
> Plxshow lastcomlist 201112

- core/lib/class.plx.motor.php
- core/lib/class.plx.utils.php
Refacto plxUtils::getValue()  (conflit 0 et empty())
Voir https://forum.pluxml.org/discussion/6925/commentaire-allow-com-passe-a-1
Dans les versions précèdentes de PluXml pour allow_com d'un article on  stocker "oui " ou "non" comme valeur. 
En utilisant "1" ou "0" comme valeurs, on révèle un bug dans plxMotor::parseArticle() et dans plxUtils::getValue() :
par de valeur par defaut pour allow_com et utilisation de $defaut si $var == '0' (PB avec empty())
> Fix valeur par défaut pour allow_com dans plxMotor::parseArticle()

- install.php
Si l'on choisit d'installer avec les données d'exemples, et après s'être connecté a l'admin (et que les notices PHP soient affichées) se produit sur toutes les page du backend un affichage disgracieux tant que le premier article subsiste en l'état.
Pour corrigé, il suffit d'éditer le premier article pour que les attributs "alt" et "title" soient ajouté au fichier ou supprimer l'article ;-)
> Install sample, 1st art missing thumb alt & title

- core/admin/statique.php
L'aperçu d'une page statique s'affiche dans  un nouvel onglet comme pour un article.
Voir mon dernier du 12 avril sur ce fil de discussion 
https://forum.pluxml.org/discussion/6964/erreur-404-apres-instal-plugin-mybetterurls
> Preview of static page on a new tab

- core/lib/class.plx.motor.php
En changeant de thème, il peut arriver qu'un template soit manquant.
On reçoit alors une notification en text/plain sans aucun lien pour revenir à la page d'accueil.
Ici on affiche la notification dans une page HTML avec menu et sidebar comme pour les articles inexistants
C'est moins perturbant pour un newbie.
> Checks if template exists in plxMotor::prechauffage

- core/lib/class.plx.motor.php
Dans plxGlob::query(), on fait un test sur &dollar;depart et &dollar;limite pour savoir si ceux sont des entiers avant d'appeler la fonction array_slice(). Sauf que plxMotor::getConfiguration() remplit plxMotor::aConf[] avec des chaines de caractères.
On se retrouve donc avec $plxMotor->aConf['bypage'] de type string qui fait échouer le test ci-avant. 
Résultat : on affiche tous les articles sur la page de blog quand certains articles sont classés dans la catégorie "home".
On a le même souci avec plxMotor::getCategories() pour la valeur de "bypage" quand on affiche les articles d'une catégorie.
Même chose pour les dimensions des images et des vignettes qui sont de type string.
> Force certaines valeurs de $plxMotor->aConf[] à être "integer"

- core/admin/parametres_avances.php
- core/admin/prepend.php
- core/lib/class.plx.admin.php
- core/lib/class.plx.motor.php
- core/lib/class.plx.utils.php
Refacto plxUtils::testModRewrite()
Corrige la réponse de la fonction si on ne détecte pas le module Rewrite de Apache (pas de serveur Apache, function apache_get_modules non disponible, module non chargé, etc...) quelque soit la valeur du paramètre $io
Force la valeur de $plxMotor->aConf['urlrewriting'] à 0 si module non détecté ou différent de 1
Met à jour le fichier .htaccess que si cette valeur est modifiée dans le back-office
> PlxUtils::testModRewrite 220824

- core/admin/parametres_avances.php
Le test ne fonctionne que si PHP est une librairie d'Apache. Ne fonctionne pas si le serveur php-fpm est employé.
> Suppression du test sur module Apache dans parametres_avances.php

- core/lib/class.plx.admin.php
plxUtils::testModRewrite() ne fonctionne pas avec un serveur PHP-FPM
> Suppression testModRewrite() dans plxAdmin::editConfiguration()

- core/lib/class.plx.utils.php
- install.php
Il est probable et plus simple de ne rien décoder/encoder maintenant que PluXml est en utf8 :)
Reste aux thèmes d’êtres en utf8 pour que les utilisateurs enregistrent leurs commentaires au bon format.
Scope : les 5 derniers commentaires de la sidebar coté public
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated
> PHP8.2 : utf8_[en|de]code deprecated

- update/index.php
Fix PLX_CONFIG_PATH & L_SAVE_SUCCESSFUL already defined
+php8.2 utf8_decode is deprecated
+classe dèja chargées par lib/config.php
Voulant faire une MAJ depuis des données d'un PluXml v5.2, il a 2 warnings !
Après avoir corrigé le fichier comme ceci,
la MAJ s'est déroulé comme un charme (elle se serait probablement bien déroulé sans)
> Fix update/index.php : Constants already defined et +

- core/lib/class.plx.token.php
Fix  'Security error : invalid or expired token' error when a form is reloaded (F5 key in navigator)
Fix plxGlob::LIFETIME to a reasonable value vs php.ini
Refacto plxGlob::generateTokenExperyDate()
> Fix plxGlob::validateFormToken() and minor bugs

- core/admin/medias.php
- core/lib/class.plx.medias.php
L'icône des documents affichait l'icône lors du clic.
Cause : la classe .thumb de l'image (maintenant .file)
De même si une image webp est animée (maintenant ok)
L'icône de la miniature est l'image originale (à la svg)
Remplace PR #720
Fix Animated webp show icon.png in thumb & zoombox : admin medias
> Fix webp animée et doc affiche icon.png : thumb & zoombox

- core/lib/class.plx.utils.php
Si un élément du tableau passé en paramètre à plxUtils::unslash() est un tableau, on rappelle cette fonction de façon récursive.
> plxUtil::unSlash : Recursivité sur les tableaux

- core/admin/theme/theme.css
> Fix icônes copier, renommer au dessus de l'entête du tableau medias lors du défilement

- core/lib/class.plx.feed.php
- core/lib/class.plx.motor.php
- core/lib/class.plx.show.php
Annonymise l'Id de l'article ds l'ancre publique du site (peut-être utile avec MyBetterUrl)
Fixe des erreurs de 2015
[mauvais index dans le lien des commentaires (2015.10.22)](https://github.com/pluxml/PluXml/commit/c03af6b5060695e98afa76952dfa2f7fb5309485) et
[refonte gestion des commentaires (2015.09.03)](https://github.com/pluxml/PluXml/commit/3371e108a3c381fb38b4d865a90ba3aeb8471894)
Donc le lien admin/comment.php est en panne depuis ce temps là 
https://github.com/pluxml/PluXml/blob/b09117cf731b73f9b56eb417f813db3dfdb399b4/core/admin/comment.php#L104
Ou alors ajouter $artId.'-' qui manque a la ligne ci-dessus 
`'/#c'.$artId.'-'.$plxAdmin...`
> Simplifie com id : #c0001-10 > #c10 & fix admin/comment link

- core/admin/comments.php
- core/admin/index.php
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/core/admin/index.php on line 314
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/core/admin/comments.php on line 88
> Fix php8.2 using ${var} in strings is deprecated

- core/lib/class.plx.admin.php
When the id of the last article is 9999, looks for the first missing id (after deletion of an article)
See https://forum.pluxml.org/discussion/7613/9999eme-article-publies-et-impossible-den-publier-un-autre
> Fix plxAdmin::nextIdArticle()

- core/lib/class.plx.motor.php
See https://forum.pluxml.org/discussion/7574/pluxml-5-9-0/p3#Comment_64863
Some plugins, officials or not, use _plxMotorPreChauffageBegin_ hook without _plxMotorDemarrageBegin_ hook for using theirs own _plxMotor::mode_ and altering _plxMotor::cible_.
This commit prevents an 404 error in this case.
These plugins must be updated !! May be they are orpheans.
> Fix for old plugins without plxMotorDemarrageBegin Hook

- core/lib/class.plx.admin.php
- core/lib/class.plx.plugins.php
- core/lib/config.php
- readme/CHANGELOG
plxAdmin::getFileStatique() always returns a string
PLX_DEBUG is set to "true"
In plxPlugins::__construct(), error is ignored in some cases :
- PLX_DEBUG is false
- $error['file'] is empty
- $error['type'] < E_DEPRECATED ( not warnings )
See :
- https://forum.pluxml.org/discussion/7669/fatal-error-type-8192-durant-edition-page-statique
- https://forum.pluxml.org/discussion/7674/php-request-shutdown-use-of-mbstring-http-input-is-deprecated
> Fix in plxAdmin::getFileStatique() and plxPlugins::__construct()

- core/lib/class.plx.admin.php
plxAdmin::getFileStatique() always returns a string if the file is missing
> Fix plxAdmin::getFileStatique()
