pluxml/PluXml

core/lib/class.plx.plugins.php

Permet de supprimer le parametre passé en parametre

Ajout fonction delParam dans la classe plxPlugin

---

core/lang/fr/update.php

Mise à jour de la langue française

---

core/lib/class.plx.show.php

proposition pour pouvoir créer des pages virtuelles sans ajout de fichier supplémentaire
http://forum.pluxml.org/viewtopic.php?pid=42151#p42151

ajout de l'action "plxShowStaticContentBegin"

---

core/lang/fr/admin.php

[BUG] Fix spelling mistake

---

core/lib/class.plx.show.php

proposition de correction pour régler le problème expliqué ici : 
http://forum.pluxml.org/viewtopic.php?id=5509
je ne suis pas sûr de bien comprendre comment fonctionne "array_multisort" donc à vérifier.

proposition correction

---

core/lib/class.plx.utils.php

See https://github.com/pluxml/PluXml/issues/246

Edit showMsg for using it with PluCss

---

core/lib/class.plx.utils.php

__Remplace PR #227__
prise en compte de <object data=".."> et <a href="#..">

plxUtils::rel2abs(..)

---

core/admin/article.php
core/lib/class.plx.motor.php

ou être embarquées (data:).
voir billets 32  et suivants sur le fil de discussion ci-dessous sur le forum
http://forum.pluxml.org/viewtopic.php?id=5168&p=2

Les vignettes d'article peuvent utiliser une url externe

---

core/lang/fr/core.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

Optimisation du code dans PlxShow::comMessage(..).
Affiche un message si le commentaire est publié.
Renvoie true si un message est affiché

PlxShow::comMessage(..)

---

core/admin/parametres_plugins.php
core/lang/fr/admin.php
core/lib/class.plx.plugins.php

Evite un bug dans core/admin/parametres_plugins.php si on affiche les
infos des plugins actifs ayant scope="site".

Vérifie l'existence d'un plugin actif dans plxPlugins::loadPlugins.

---

core/lib/class.plx.show.php
core/lib/class.plx.utils.php

cf. http://forum.pluxml.org/viewtopic.php?id=6291

Modif plxShow::artThumbnail() et plxUtils::thumbName()

---

feed.php
index.php
install.php
sitemap.php

Il y a aussi des include dans les fichiers *.php situés à la racine du site.

Suppress. des () pour include à la racine du site

---

core/lib/class.plx.date.php

Après quelques essais, la variable $value est a 'false' lorsque l'on consulte les archives d'une année
https://forum.pluxml.org/viewtopic.php?pid=57710#p57710

Fix archives par années

---

core/admin/auth.php

Ça fait un moment que je le vois, il est probable qu'il serve a rien(?)
Il y a un exit avant ;)

auth.php : A quoi sert ce code, il n'est jamais lancé :)

---

core/lib/class.plx.admin.php
readme/CHANGELOG

Fix #343 affichage article suite suppression categorie

---

core/lib/class.plx.utils.php

ajout paramètre extra comme dans plxUtils::printInput
optimisation code

Mise à jour de plxUtils::printArea

---

core/lib/class.plx.utils.php

Retourne un tableau associatif comme dans les versions précèdentes

Fix plxUtils::getLangs()

---

core/lib/class.plx.token.php

Actuellement, avec plxToken::getTokenPostMethod(), il est tout à fait possible d'avoir un token avec comme valeur un seul chiffre !
- Avec ce PR, on s'assure que le token aura par défaut toujours une valeur de 32 caractères, non seulement des chiffres, mais aussi des lettres majuscules et minuscules.
- Dans le cas d'une page HTML avec plusieurs formulaires, on peut récupérer la valeur de $token et l'employer dans plusieurs formulaires. Dès qu'on valide un formulaire, on efface l'unique $_SESSION['formtoken'][$token]. Actuellement on n'efface que le token du formulaire posté et on oublie les tokens des autres formulaires
- Dès qu'un formulaire est validé, on vérifie s'il ne traine pas de vieux tokens (plus vieux que 3600 secondes )
- on privilégie des constantes de class pour éviter …

Enhancement for plxToken class

---

core/lib/class.plx.utils.php

minor fix dans plxUtils::sendmail

---

core/admin/medias.php
core/lib/class.plx.medias.php
core/lib/class.plx.utils.php

Creation des constantes THUMB_WIDTH et THUMB_HEIGHT pour plxUtils
Supprime parametres inutiles pour plxUtils::makeThumb() dans
plxMedias::_uploadFile()

Supprime vilain effet redim. colonnes dans medias.php

---

core/admin/top.php
core/lib/class.plx.utils.php

on splitte le code HTML pour le menu dans core/admin/top.php

Suppression du double attribut title dans plxUtils::formatMenu()

---

core/lib/class.plx.utils.php

Voir discussion :
https://forum.pluxml.org/discussion/6697/2-bugs-dans-la-creation-des-pages-statiques

Prise en compte des liens externes pour les urls des pages statiques

---

core/lib/class.plx.feed.php
core/lib/class.plx.motor.php

FIX #380 plxAdmin and plxFeed regex refacto (also based on https://forum.pluxml.org/discussion/comment/45486/#Comment_45486)

FIX #380 plxMotor and plxFeed regex refacto

---

core/admin/categorie.php
core/admin/categories.php
core/admin/comment.php
core/admin/comment_new.php
core/admin/comments.php
core/admin/statique.php
core/admin/statiques.php
core/admin/top.php
core/lib/class.plx.admin.php
core/lib/config.php

Passage des paramètres inconsistant

Refacto plxAdmin::checkProfil

---

install.php

Formatage code - PB fusion ?

---

core/admin/comments.php
core/lib/class.plx.motor.php
readme/CHANGELOG

FIX issue https://github.com/pluxml/PluXml/issues/419

FIX Comments list sorting #419

---

themes/defaut/commentaires.php

Flux des commentaires uniquement si les commentaires sont activés

Affichage conditionnel du Flux des commentaires

---

core/lib/class.plx.token.php

- Fix plxToken::validateFormToken() :
variable $limit non définie
- plxToken::getTokenPostMethod()
paramètre $html non traité

Divergence avec branche master

---

core/admin/statique.php
core/lib/class.plx.admin.php

Petite correction pour la sauvegarde du template des pages statiques
Tri des templates dans l'édition d'une page statique

Petit correction

---

core/lib/class.plx.admin.php

Fix config pour feuille CSS perso côté admin

Fix config pour feuille CSS personnalisé côté admin

---

core/admin/top.php

Pour personnaliser le back-office selon le profil utilisateur.

admin/top.php: ajout d'une class profil-x x entre 0 et 5

---

core/admin/medias.php
core/admin/theme/theme.css
core/lib/class.plx.medias.php
core/lib/medias.js
core/lib/visual.js

fichier medias.php :
- Quand on ouvre le popup pour un nouveau dossier, le champ de saisie a le focus
- Après validation, le nouveau dossier est affiché
- code HTML plus lisible
- Tri des médias côté navigateur avec Javascript (évite les aller-retours entre serveur et navigateur à chaque tri)

Medias 2005

---

core/admin/auth.php
core/admin/foot.php
core/admin/prepend.php
core/admin/theme/css/theme.css
core/lib/class.plx.admin.php
core/lib/class.plx.date.php
core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php
core/lib/mediasManager.js
index.php
readme/CHANGELOG

Test version PHP dès le début
Suppression include
option "samesite" pour cookie de session

Refacto core/admin/prepend.php

---

core/lib/class.plx.timezones.php

Peut-être plus judicieux, si changement de nom de classe

plxTimezones::timezones() to self

---

themes/defaut/css/theme.css

Corrige le menu quand il y a plusieurs pages statiques dans un même groupe

Fix CSS pour menu dans theme defaut

---

core/lib/class.plx.admin.php
core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
themes/defaut/css/theme.css

Fix $instance pour plxMotor, plxAdmin, plxFeed
Fix css3 menu thème défaut

Fix $instance pour plxMotor, plxAdmin, plxFeed

---

core/admin/medias.php
core/admin/theme/css/theme.css
core/lib/class.plx.medias.php

Affiche les vignettes pour les fichiers SVG dans le gestionnaire de médias

Svg preview 200828

---

core/lib/class.plx.motor.php

Voir post sur le forum :
https://forum.pluxml.org/discussion/6829/souci-de-pagination-dans-la-5-8-4

Prechauffage 200911

---

core/lib/class.plx.show.php

Les articles à modérer sont maintenant exclus de la liste

Minor fix : regex $motif dans plxShow::lastArtList()

---

core/lib/class.plx.motor.php

Refacto plxMotor::urlRewrite() avec parse_url()
Voir https://forum.pluxml.org/discussion/6940/diese-dans-urlrewrite

Plxmotor-urlrewrite-200127

---

core/lib/class.plx.motor.php

voir discussion sur le forum :
https://forum.pluxml.org/discussion/comment/61626#Comment_61626
N.B. : La génération de $motif dans core/admin/index.php est erronée.
Voir branche admin-table-overflow-201120 sur dépôt https://github.com/kazimentou/PluXml

Plxmotor art info from filename 210201

---

core/lib/class.plx.admin.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

Voir discussion sur forum :
https://forum.pluxml.org/discussion/6980/bogue-admin-lajout-dune-categorie-dans-la-page-d-edition-article-peut-en-ecraser-une-autre#latest

Plxadmin nextidcategory

---

core/admin/article.php
core/admin/categorie.php
core/admin/parametres_affichage.php
core/admin/parametres_themes.php
core/admin/statique.php
core/lib/class.plx.feed.php
core/lib/class.plx.glob.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

filtrage des noms de fichiers articles, pages statiques et commentaires
Dans plxGlob::initCache, $type peut être une expression régulière pour filtrer les fichiers

plxGlob enhanced

---

core/admin/parametres_infos.php
core/admin/top.php
core/lang/de/core.php
core/lang/en/core.php
core/lang/es/core.php
core/lang/fr/core.php
core/lang/it/core.php
core/lang/nl/core.php
core/lang/oc/core.php
core/lang/pl/core.php
core/lang/pt/core.php
core/lang/ro/core.php
core/lang/ru/core.php
core/lib/class.plx.motor.php
core/lib/class.plx.plugins.php
core/lib/config.php
update/class.plx.updater.php

les versions des données sont désynchronisées des versions de PluXml.
Permet de revenir sur une version précèdente de PluXml si le format des données n'a pas changé.

New constant PLX_VERSION_DATA

---

core/lib/class.plx.glob.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

Voir https://forum.pluxml.org/discussion/7265/static-et-articles-en-page-daccueil

plxShow::staticInclude

---

core/lang/oc/admin.php

Just a quick change to translate

lang: Occitan

---

core/lib/class.plx.admin.php

Filtre la valeur pour PLX_CONFIG_PATH dans plxAdmin::editConfiguration()

---

core/admin/article.php
core/admin/theme/theme.css
core/lib/class.plx.msg.php
core/lib/visual.js

Enhance plxMsg, Fix JS script in article.php

---

core/lib/class.plx.glob.php

Fix plxGlob::getInstance()

---

core/lib/class.plx.motor.php
core/lib/class.plx.utils.php

Remplace la fonction getValue() par les fonctions getTagIndexValue() pour analyser les fichiers XML

Plxutils gettagvalue

---

core/admin/parametres_themes.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php
core/lib/class.plx.themes.php

if selected theme does not exists or not lang in this theme, then switch to "defaut" theme or an other theme.

New class plxThemes

---

core/admin/prepend.php
core/lang/de/admin.php
core/lang/de/install.php
core/lang/en/admin.php
core/lang/en/install.php
core/lang/es/admin.php
core/lang/es/install.php
core/lang/fr/admin.php
core/lang/fr/install.php
core/lang/it/admin.php
core/lang/it/install.php
core/lang/nl/admin.php
core/lang/nl/install.php
core/lang/oc/admin.php
core/lang/oc/install.php
core/lang/pl/admin.php
core/lang/pl/install.php
core/lang/pt/admin.php
core/lang/pt/install.php
core/lang/ro/admin.php
core/lang/ro/install.php
core/lang/ru/admin.php
core/lang/ru/install.php
core/lib/class.plx.admin.php
core/lib/class.plx.utils.php
core/lib/config.php

Emploi ob_start()/ob_get_clean() pour générer document XML
Nouvelle constante XML_HEADER
Modif de plxUtils::strCheck() (voir strip_tags)
plxUtils::strCheck() et strip_tags() employés pour sauvegarde fichiers XML
Mise à jour fichiers linguistiques

Refacto plxAdmin for beautiful XML

---

core/admin/top.php

Just in index.php and $_SESSION['profil'] == 0

moderate warning for install.php

---

core/admin/foot.php
core/admin/prepend.php
core/admin/top.php
core/lib/class.plx.admin.php
core/lib/class.plx.motor.php
core/lib/config.php

move HTACCES_FILE from admin/prepend.php to lib/class.plx.admin.php

---

core/admin/parametres_avances.php
core/lib/class.plx.admin.php
core/lib/class.plx.utils.php
core/lib/config.php

Better controls for input values

Fix plxAdmin::editConfiguration()

---

core/lib/class.plx.admin.php
core/lib/class.plx.glob.php
core/lib/class.plx.motor.php

Prepare update for plxFeed class

Fix plxMotor::__construct()

---

core/lib/class.plx.admin.php

Fix in plxAdmin::editConfiguration() for .htaccess

Fix for .htaccess

---

core/admin/theme/images/rss.svg
core/lib/class.plx.admin.php
core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php
core/lib/config.php
feed.php
themes/defaut/categorie-full-width.php
themes/defaut/categorie.php
themes/defaut/commentaires.php
themes/defaut/css/theme.css
themes/defaut/footer.php
themes/defaut/home.php
themes/defaut/tags.php
themes/defaut/user.php

Plx feed 221220

---

core/lang/de/core.php
core/lang/en/core.php
core/lang/es/core.php
core/lang/fr/core.php
core/lang/it/core.php
core/lang/nl/core.php
core/lang/oc/core.php
core/lang/pl/core.php
core/lang/pt/core.php
core/lang/ro/core.php
core/lang/ru/core.php
core/lib/class.plx.admin.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

for plxShow::authorList() and plxMotor::prechauffage()

plxUtils::urlify() for username

---

core/lib/class.plx.motor.php

Checks if ^$capture[2] exists

---

config.php
core/lib/class.plx.motor.php
core/lib/config.php
data/articles/.htaccess
data/commentaires/.htaccess
data/configuration/.htaccess
data/statiques/.htaccess
install.php
plugins/.htaccess

Refacto install.php
New constant : DEFAULT_CONFIG, used by plxMotor and install.php
Fix config.php for install.php

Refacto plxMotor::getConfiguration()

---

core/lib/class.plx.motor.php

Fix regex in plxMotor::prechauffage()
Add "pin" category

Refacto plxMotor::prechauffage()

---

.htaccess
core/admin/article.php
core/admin/index.php
core/admin/theme/theme.css
core/lang/de/admin.php
core/lang/en/admin.php
core/lang/es/admin.php
core/lang/fr/admin.php
core/lang/it/admin.php
core/lang/nl/admin.php
core/lang/oc/admin.php
core/lang/pl/admin.php
core/lang/pt/admin.php
core/lang/ro/admin.php
core/lang/ru/admin.php
core/lib/class.plx.admin.php
core/lib/class.plx.glob.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php
themes/defaut/categorie-full-width.php
themes/defaut/categorie.php
themes/defaut/css/theme.css
themes/defaut/home.php
themes/defaut/tags.php
themes/defaut/user.php

Articles épinglés pour s'afficher en tête de liste

Pinned articles

---

core/lib/class.plx.motor.php
core/lib/class.plx.show.php
themes/defaut/commentaires.php

* new function plxShow::articleAllowComs()

Refacto plxShow

---

core/admin/article.php
core/admin/auth.php
core/admin/parametres_plugins.php
core/admin/prepend.php
core/admin/top.php
core/lib/class.plx.admin.php
core/lib/class.plx.motor.php
core/lib/class.plx.utils.php

Enhance menu admin

---

core/admin/index.php
core/lib/class.plx.show.php

Fix count of articles in plxShow for archives and users

drop subscriber profil in admin/index.php

---

core/lang/oc/admin.php
core/lang/oc/core.php
core/lang/oc/update.php
themes/defaut/lang/oc.php

i18n: Occitan translations updated

---

core/admin/top.php

[6.0.0-dev] Admin: mauvais lien profil #544

Update top.php branche 6.0

---

core/admin/top.php

[6.0.0-dev] Admin: mauvais lien profil #544

Update top.php branche 6.0-search

---

core/lib/class.plx.show.php
themes/defaut/header.php

See https://github.com/pluxml/PluXml/issues/669#issuecomment-1813348024
Add new param $link_homepage in plxShow::staticList()
New constants STATIC_LIST_FORMAT and STATIC_LIST_FORMAT_GROUP for plxShow class.
Default values for $format and $format_group params in plxShow::staticList()

Smart link for homepage in menubar

---

core/lib/class.plx.admin.php

Fix plxAdmin::editArticle() for published date
https://forum.pluxml.org/discussion/7574/pluxml-5-9-0#Comment_64565

Fix plxAdmin::editArticle() pour published date

---

core/lib/class.plx.feed.php
core/lib/class.plx.show.php
sitemap.php

Fix regex expressions for searching articles

Fix regex expressions for searching articles

---

core/admin/parametres_avances.php

Change in core/admin/parametres_avances.php

Checks if robots.txt exists before displaying

---

core/lib/class.plx.show.php

Duplicate display homepage in categories of article
Optimisation of code

Fix plxShow::artCat()

---

core/lib/class.plx.motor.php

Fix plxMotor::prechauffage() when articles classified in homepage and every publish later

Fix plxMotor::prechauffage() for homepage

---

core/admin/foot.php
core/admin/js/visual.js
core/admin/profil.php
core/admin/top.php
install.php

check strenght of password in install.php and  profil.php
Fix required attribute in install.php

Install 240109

---

core/lang/oc/core.php

Just so it's perfect for next release :D

i18n: small update for Occitan

---

update/index.php

+include typo
+plx_session_start

plx_session_start : update/index.php

---

core/admin/index.php
core/admin/theme/theme.css
core/lang/de/admin.php
core/lang/en/admin.php
core/lang/es/admin.php
core/lang/fr/admin.php
core/lang/it/admin.php
core/lang/nl/admin.php
core/lang/oc/admin.php
core/lang/pl/admin.php
core/lang/pt/admin.php
core/lang/ro/admin.php
core/lang/ru/admin.php
core/lib/class.plx.admin.php

Add button for making again tags.xml file
Select user/author or category inside the table of articles
No link for no_comment (validated or not)
Adjust widths of columns in the table
Force tags to lowercase for saving in tags.xml file

Refacto core/admin/index.php - force tags to lowercase()

---

core/lang/oc/admin.php

i18n: Update for Occitan

---

core/admin/comment.php
core/admin/comment_new.php
core/admin/comments.php
core/lib/class.plx.admin.php
core/lib/class.plx.motor.php

See https://forum.pluxml.org/discussion/7574/pluxml-5-9-0

Many fixes for comments of articles

---

core/admin/comments.php
core/admin/index.php
core/admin/theme/plucss.css
core/admin/theme/theme.css
core/admin/top.php
core/lib/class.plx.utils.php

Fix plxUtils::printPagination()
checks if fileExists install.php in index.php vs top.php. Display notice only on the first page of articles
Update css rules

Refacto core/admin/index.php

---

core/admin/js/medias.js
core/admin/medias.php
core/admin/theme/theme.css

Tri tableau des medias - @author Jean-Pierre Pourrez "bazooka07" - 2020-05-12

All columns sort medias & breadcrumb by medias.js

---

core/admin/medias.php

- Fix $plxMediasRoot from users profil in medias.php
- Short tags for echo in medias.php

Admin-medias-240125

---

core/admin/js/medias.js
core/admin/medias.php
core/admin/theme/theme.css
core/lib/class.plx.medias.php
core/lib/class.plx.utils.php

Short tags for "<?php echo " in admin/medias.php
css loader is displaying for heavy picture in the zoombox
new constants THUMB_WIDTH and THUMB_HEIGHT in  plxUtils class
add  anonymous function in medias.js ( effet de bord pour les variables )
Fix for SVG images in medias.php

Fix medias.php

---

core/admin/medias.php

Look at redirection after processing $_POST

Minor refacto in medias.php about $_POST

---

core/lib/class.plx.motor.php
core/lib/class.plx.utils.php

Fix % urlTemplate error in plxUtils::printPagination
and avoid "div by zero "
Avoid null values for bypage... in plxMotor::getConfiguration()

% urlTemplate error in plxUtils::printPagination

---

core/admin/article.php
core/lib/class.plx.admin.php

See https://forum.pluxml.org/discussion/comment/64709

Fix plxAdmin::editArticle() and design in article.php

---

core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
core/lib/class.plx.record.php

Prints directly the result. No returned value.
New function plxRecord::lastUpdateDate()
See https://forum.pluxml.org/discussion/comment/64713#Comment_64713

Fix getRss..() for plxFeed

---

core/lib/class.plx.feed.php
feed.php

See https://forum.pluxml.org/discussion/comment/64717#Comment_64717

Fix plxFeed and feed.php

---

core/lib/class.plx.feed.php

And new hook plxFeedPrintRSSTop

Fix plxFeed::printRSSTop() if no record

---

core/lib/class.plx.feed.php

See https://forum.pluxml.org/discussion/comment/64733#Comment_64733

plxFeed::prechauffage() returns 404 error for bad query

---

core/admin/parametres_plugin.php
core/lib/class.plx.admin.php
core/lib/class.plx.plugins.php
core/lib/config.php

Refacto plxAdmin::checkProfil()
Checks if defined('PLX_CONFIG_PATH') in lib/config.php
More info at https://forum.pluxml.org/discussion/comment/64757#Comment_64757

Fix parametres_plugin.php

---

core/admin/statiques.php

Required statiques Titles + data-id order

---

core/admin/parametres_plugins.php

Fix plugins list with dates

---

core/lang/fr/core.php
core/lib/class.plx.capcha.php

see :
https://forum.pluxml.org/discussion/comment/64677/#Comment_64677

Fix capcha, simplify template chars + fr typo

---

core/admin/top.php

See https://forum.pluxml.org/discussion/7610/non-unicite-dun-attribut-id-dans-le-menu-dadministration-de-la-partie-admin

Fix menu admin

---

core/admin/theme/theme.css
core/lib/class.plx.utils.php

See https://forum.pluxml.org/discussion/7610/non-unicite-dun-attribut-id-dans-le-menu-dadministration-de-la-partie-admin

Fix pluxUtils::formatmenu()

---

core/admin/parametres_edittpl.php
core/admin/parametres_themes.php
core/lib/config.php

See https://forum.pluxml.org/discussion/comment/64805#Comment_64805
New constants from PLX_RESSOURCES_URL in core/lib/config.php :
- PLX_RESSOURCES_LINK
- PLX_RESSOURCES_PLUGINS_LINK
- PLX_RESSOURCES_THEMES_LINK

Fix link for themes ressource

---

core/admin/medias.php

Bad short tag for PHP <?= for checkbox in the table

Fix admin/medias.php

---

core/lib/class.plx.admin.php

See https://forum.pluxml.org/discussion/7615/redondance-daffectation-dune-variable-dans-class-plx-admin-dans-version-5-9-rc6

Plx admin editcategories 240224

---

core/lib/class.plx.admin.php

See https://forum.pluxml.org/discussion/comment/64831#Comment_64831

Refacto plxAdmin-editStatiques()

---

core/lib/class.plx.feed.php

See https://forum.pluxml.org/discussion/7618/argument-manquant-dans-lappel-dune-methode-dans-le-fichier-class-plx-feed-php

Fix plxFeed::getAdminComments()

---

core/lib/class.plx.feed.php
core/lib/class.plx.show.php
feed.php

See https://forum.pluxml.org/discussion/7614/probleme-avec-le-flux-rss-et-longlet-recherche#Comment_64845

Fixes for RSS feed

---

core/lib/class.plx.motor.php

Fix plxMotor::prechauffage()

---

core/admin/index.php
core/admin/parametres_users.php
core/lang/de/core.php
core/lang/en/core.php
core/lang/es/core.php
core/lang/fr/core.php
core/lang/it/core.php
core/lang/nl/core.php
core/lang/oc/core.php
core/lang/pl/core.php
core/lang/pt/core.php
core/lang/ro/core.php
core/lang/ru/core.php
core/lib/class.plx.admin.php
core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
core/lib/class.plx.plugins.php
core/lib/class.plx.show.php
core/lib/class.plx.utils.php
core/lib/config.php
index.php
install.php

- On the front-side, urls depend of the language of the site
- Better management for the language of site 
If logged, the user looks at the site with his own language instead of the default language of the site, included preview of the article
- Add flags for countries

i18n in urls

---

core/lib/class.plx.show.php

And :
- drop unuseful "echo" instructions
- replace "\n" by PHP_EOL

Fix plxShow::urlPostsRssFeed() for urlrewriting (for RSS feeds)

---

core/lib/class.plx.motor.php

See https://forum.pluxml.org/discussion/comment/64875#Comment_64875

Minor fixes in plxMotor::prechauffage()

---

core/lang/de/core.php
core/lang/en/core.php
core/lang/es/core.php
core/lang/fr/core.php
core/lang/it/core.php
core/lang/nl/core.php
core/lang/pl/core.php
core/lang/pt/core.php
core/lang/ro/core.php
core/lang/ru/core.php
core/lib/class.plx.motor.php
themes/defaut/css/theme.css
themes/defaut/erreur.php

And more :
Tune erreur.php template in defaut theme
Don't say a message with "PluXml" on the front-side !!

Add erreur mode in plxMotor::demarrage()

---

core/admin/comment.php

Add `required` class in author and content label
Site link in label + rel noreferrer
Mail link in label + var $mail (DRY)
Add missing &nbsp;

Refacto admin comment

---

core/admin/article.php
core/admin/statique.php
core/admin/statiques.php
core/lib/class.plx.feed.php
core/lib/class.plx.motor.php
core/lib/class.plx.show.php

?article to L_ARTICLE_URL
?static to L_STATIC_URL
?categorie to L_CATEGORY_URL
?static to L_STATIC_URL
?tag to L_TAG_URL
?user to L_USER_URL
L_COMMENTS_URL
?' . L_••• & rssAttachment (feed filename)
Fix plxShow::authorName() : plxUtils::urlify($userName)

core multilingual

---

core/admin/comment.php
core/admin/comments.php
core/admin/js/medias.js
core/admin/medias.php
core/admin/parametres_plugins.php
core/admin/theme/theme.css
core/admin/top.php

In medias.php, don't link directly for an file image but displays an image inside an anchor tag with zoombox.
Otherwise, add download attribute in the anchor tag if the file is not an image in good format
Add _rel="noreferrer nofollow" to the anchor tag.
Add name="referrer" with noreferrer in meta tag for the head in top.php

Security 240316

---

core/admin/parametres_plugin.php
core/admin/statique.php
core/admin/statiques.php
core/lib/class.plx.admin.php
core/lib/class.plx.motor.php
core/lib/class.plx.plugins.php
core/lib/class.plx.show.php
index.php

and refacto plxShow::pageTitle()

Refacto for static-pages without content file

---

core/admin/article.php

See https://forum.pluxml.org/discussion/7634/plusieurs-onglets-pour-un-meme-article-en-modification

Fix preview of article is always displaying in the same tab or window.

---

core/admin/article.php

preview article is always displaying in the same tab or window.

Fix in article.php

---

install.php

Fix lang for user's selection in install.php

Fix lang for user's selection

---

core/lib/class.plx.plugins.php

List of inactive plugins is always displaying.
Even with wrong plugins :
Some plugins are not ready for PHP > 8.0.0

List of inactive plugins

---

core/admin/article.php

Avoid a lot of onclick="this.form.target='_self';return true;" in article.php

Use of formtarget attribute in submit element

---

core/lib/class.plx.medias.php
core/lib/class.plx.utils.php

See https://forum.pluxml.org/discussion/7763/error-2-core-lib-class-plx-utils-php-ligne-660

Fix for making thumbnails from medias

---

core/lib/class.plx.plugins.php

See https://forum.pluxml.org/discussion/7756/fatal-error-type-2

Displays informations about enabled plugins when a fatal error occurs

---

core/lib/class.plx.admin.php

Fix plxAdmin::resetPasswordToken()

plxAdmin-resetPasswordToken

---

core/lib/class.plx.admin.php

Fix plxAdmin::resetPasswordToken()

plxAdmin-resetPasswordToken-fix

---

core/lib/class.plx.date.php

Accept also ISO format (2024-07-14T12:30)

Refacto plxDate

---

core/lib/class.plx.admin.php

See https://forum.pluxml.org/discussion/7769/anciens-users-et-rgdp

Erase personal datas when a user is deleted

---

core/lib/class.plx.motor.php

Give default date in static page for date_creation & date_update

Fix plxMotor::getStatiques() for dates

---

core/admin/article.php
core/admin/categorie.php
core/admin/parametres_affichage.php
core/admin/statique.php
core/lib/class.plx.glob.php

Plx glob init cache 250106

---

core/admin/categories.php
core/admin/index.php
core/admin/theme/theme.css
core/lang/de/admin.php
core/lang/en/admin.php
core/lang/es/admin.php
core/lang/fr/admin.php
core/lang/it/admin.php
core/lang/nl/admin.php
core/lang/oc/admin.php
core/lang/pl/admin.php
core/lang/pt/admin.php
core/lang/ro/admin.php
core/lang/ru/admin.php

for index.php and categories.php in core/admin
In articles.php filter by categories which are count of articles &gt; 1

Displays count of articles per category in back-office

---

core/lib/class.plx.admin.php
core/lib/class.plx.motor.php

Don't store article id in tags.xml without tags

plxAdmin-editArticle-tags

---

core/lib/class.plx.admin.php

Don't store article Id in tags.xml without tags

plxAdmin-editArticle-without_tags

---

core/lib/class.plx.utils.php

use of &lt;label&gt; as block in plxUtils::printInputRadio()

Refacto plxUtils::printInputRadio

---

core/lib/class.plx.motor.php

Refacto plxMotor::urlrewrite() for better urls

Refacto plxMotor-prechauffage() for betterurls

---

core/admin/statiques.php
core/lang/de/admin.php
core/lang/en/admin.php
core/lang/es/admin.php
core/lang/fr/admin.php
core/lang/it/admin.php
core/lang/nl/admin.php
core/lang/oc/admin.php
core/lang/pl/admin.php
core/lang/pt/admin.php
core/lang/ro/admin.php
core/lang/ru/admin.php
core/lib/class.plx.admin.php

Add filter by group for static pages
Use datalist tag for input group

Add filter by group for static pages

---

core/admin/parametres_edittpl.php
core/lib/class.plx.motor.php
core/lib/class.plx.utils.php

Fix use of scandir()
